# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            its 
description:      'tanácsadás a digitális üzletben'
url:              https://its.hu
baseurl:          /

author:
  name:           'its'
  url:            https://its.hu