# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            its 
description:      'tanácsadás a digitális üzletben'
url:              https://its.hu
baseurl:          /

# Set permalink
permalink: articles/:title
paginate:         10

author:
  name:           'its'
  url:            https://its.hu


gems:
  - jekyll-paginate
  - jekyll-sitemap